### ISSUE TITLE
Patterns that appear before the module name.

### ISSUE THREAD

**Issue by miau** [itchyny/rexdep#2]
Sometimes patterns appear before the module name.

Example:

```
$ cat Bug.php
<?php
/**
 * @Entity(repositoryClass="BugRepository")
 * @Table(name="bugs")
 **/
class Bug
{
    //...
}

$ rexdep --pattern '\brepositoryClass=.(\w+).' --module '^class\s+(\w+)' Bug.php
Bug.php BugRepository
```

It is appreciated if rexdep would have a option to put `Bug BugRepository` in this case.

**Comment by itchyny** [comment]
Thank you for your feature request. I implemented `--reverse` option. Please reinstall and then check if it works as you want. I'll create a tag and release a new brew rule after you confirmed.

**Comment by miau** [comment]
Thank you for your implementation. The `--reverse` option solves my problem above, but my example was badly simplified.

Here is a bit more complicated example:

```
$ cat Bug.php
<?php
/**
 * @Entity(repositoryClass="BugRepository")
 * @Table(name="bugs")
 **/
class Bug
{
    /**
     * @ManyToMany(targetEntity="Product")
     **/
    protected $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }
}

$ rexdep --pattern '\b(?:repositoryClass|targetEntity)=.(\w+).|new\s(\w+)' --module '^class\s+(\w+)' Bug.php
Bug.php BugRepository
Bug ArrayCollection
Bug Product

$ rexdep --reverse --pattern '\b(?:repositoryClass|targetEntity)=.(\w+).|new\s(\w+)' --module '^class\s+(\w+)' Bug.php
Bug BugRepository
```

What I would like to get is:

```
Bug BugRepository
Bug ArrayCollection
Bug Product
```

**Comment by itchyny** [comment]
With the `--reverse` option, rexdep regards the module name (`--module`) appears after the dependants (`--pattern`), as the title of this issue says. I don't know much of php but probably you are willing to extract different kinds of dependency relations. The following command works for the dependency relation of repositoryClass,

```
rexdep --reverse --pattern '\brepositoryClass=.(\w+)' --module '^class\s+(\w+)' Bug.php
```

and the following command works for the classes each class actually uses.

```
rexdep --pattern '\bnew\s(\w+)' --module '^class\s+(\w+)' Bug.php
```

**Comment by miau** [comment]
Thank you again. With your suggestion, I have achieved my goal. If I encounter a hard-to-solve problem with the `--reverse` option, I will make another feature request.

**Comment by itchyny** [comment]
OK. Thanks for your feature request.
