### ISSUE TITLE
basic example on windows-64

### ISSUE THREAD

**Issue by valeriocos** [itchyny/rexdep#4]
First of all, congratulation for the tool, it looks really nice!
I was trying to execute the [basic example](https://github.com/itchyny/rexdep#usage) on Windows, but I found a small problem. 
The following command returns nothing if single quotation marks are used:
```
input: rexdep --p 'import\s+(\S+)' --format json test1.txt
output: {}
```
however it works with double quotation marks
```
input: rexdep --p "import\s+(\S+)" --format json test1.txt
output: {"test1.txt": ["test2, ... ]}
```

**Comment by valeriocos** [comment]
Also the [other examples](https://github.com/itchyny/rexdep#examples) do not work.
For instance, the following command raises an error
```
rexdep -p "import (\S+)" --format json PyGitHub\PyGitHub\github\*.py
```
Instead the command below works, although non-py files are also returned
```
rexdep -p "import (\S+)" --format json --recursive PyGitHub\PyGitHub\github -e py
```

**Comment by itchyny** [comment]
Thank you. Right, single quotes does not work on Windows and I think I should mention on it. I prefer single quotes due to the C language examples; `--pattern '^\s*#include\s*"(\S+)"'`. Does ` "^\s*#include\s*\"(\S+)\""` work on Windows? I don't have Windows environment and I can't test.

**Comment by valeriocos** [comment]
Yes, it works (I have tried with the git example). Below you can see the command and the output.
```rexdep -p "^\s*#include\s*\"(\S+)\"" --format json --output ./output.json --recursive git```
[output.zip](https://github.com/itchyny/rexdep/files/1117027/output.zip)

I have also tried to filter by extension with -e, but all files are returned
